### ISSUE TITLE
Some capital letters are too small

### ISSUE THREAD

**Issue by Nabav** [GehDoc/vscode-textile-preview#67]
**Textile Language Features:** v1.3.20
**VS Code:** 1.71.1
**Operating system:** Debian 11

Is there a way to keep the capital letters always the normal size?

Example:
![image](https://user-images.githubusercontent.com/24389873/190340271-9e799d2e-3d80-4122-891f-6ff2c2fd44f2.png)

**Comment by GehDoc** [comment]
Closed here : 3a20b3b35c5e0dc065c7fa9f6db7db2713157296
Thank you for reporting this !

**Comment by Nabav** [comment]
Thank you for the quick fix.
