### ISSUE TITLE
Table header row is always centered horizontally

### ISSUE THREAD

**Issue by Nabav** [GehDoc/vscode-textile-preview#76]
**Textile Language Features:** `v1.3.23`
**VS Code:** `v1.81.1`
**Operating system:** Debian 11

**Describe the bug**
The cells of the first row of a table are centered disregarding formatting characters.

**To Reproduce**
Use this and preview:

```textile
|_. Col1          |_=. Col2        |_.  Col3          |
|=.  col1 row1    |   col2 row1    |=.  col3 row1     |
|=.  col1 row end |   col2 row end |=.  col3 row end  |
```

**Expected behavior**
As rendered by textile-lang.com, just the second column is centered as specified by `_=.`, the other two columns are not centered horizontally in the first row.

![image](https://github.com/GehDoc/vscode-textile-preview/assets/24389873/e5910559-9087-4b63-8e7c-8ebd263ef7b7)

**Additional context**
This is what is currently rendered:

![image](https://github.com/GehDoc/vscode-textile-preview/assets/24389873/df38c28d-a826-42c8-bb35-f433de3abab9)

**Comment by GehDoc** [comment]
Confirmed : Electron's stylesheet centers text by default on table header cells with `text-align: -internal-center;`
